### ISSUE TITLE
You have somthing

### ISSUE THREAD

**Issue by milax** [rodikno/Automation_course#22]
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as
Shd';sadl a';dlsa';lsa';dl';sld';sad';asl';saas;as'';ALD;'SA'SA'sa';\d;as

**Comment by d-konovalov** [comment]
@milax 
тебе ж на ужин надо идти
что ты тут делаешь?

**Comment by milax** [comment]
@d-konovalov это я пытался доказать товарищу Родиону, что форма не лочится при сабмите )

**Comment by d-konovalov** [comment]
@milax 
так  а как же ужин? :)

**Comment by milax** [comment]
ужин - done :)
ишью можно закрывать)

**Comment by rodikno** [comment]
Verified on one glass of IPA, one glass of Whisky, some meal and dessert.
